[functions.create-banner-checkout]
enabled = true
verify_jwt = false
entrypoint = "./functions/create-banner-checkout/index.ts"

[functions.banner-impresion]
enabled = true
verify_jwt = false
entrypoint = "./functions/banner-impresion/index.ts"

[functions.stripe-webhook]
enabled = true
verify_jwt = false

[functions.create-checkout-session]
enabled = true
verify_jwt = false
